name: Frontend CI (build only)

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop, feature/** ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      #- name: Lint
      #  run: npm run lint --if-present

      - name: Build (Vite + tsc -b)
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
